#This is my vour for my 2025 tour, ONLY 2 YEARS LEFT 
###
#Algorithm for is 
# input - ALG - ouput
#
#Behind the computing: Computational Procedures 
#Buy a book name >>>>> The art of computer Programming #
#Algorithms in the searching
## https://www.manning.com/books/grokking-algorithms
####CLRS
 # THere is only to 

# 1.the output must be sort according to the provided order
# 2.output must be sorted according to <= 
# 3.Bubble Sort/ Magic Sort / Heap Sort / Quick Sort  } - Tim sort   most use = quicksort 
####pseudo-code conventions
####Insertion sort procedure
####insert( A, j) 
        # for i = j - 1 down to (i) 
        #   if A[i] >   A[i+1] : 
        #     swap ( A[i], A[i+1])
        #   else : 
        #      break;

        # for j = 1 up to n : 
        #     insert(A,j) 

# Computation Complaxity 
#    Time: Independent 
#    Space:Memory 


#The best case of the insertion: Break when the first insertion happen 
#

def fun(n,x):
    counter = n
    amount = 0
    while counter > 0:
        amount = amount + x
        counter = counter - 1
    return amount

### Cost model for each operation cost 






